---
sidebar: sidebar 
permalink: task_getting_started_aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, tiering, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create 
summary: 只需几步即可开始使用适用于 AWS 的 Cloud Volumes ONTAP 。 
---
= Cloud Volumes ONTAP for AWS 入门
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
只需几步即可开始使用适用于 AWS 的 Cloud Volumes ONTAP 。



==== 创建连接器

[role="quick-margin-para"]
如果您没有 link:concept_connectors.html["连接器"] 但是，客户管理员需要创建一个。 。

[role="quick-margin-para"]
在创建首个 Cloud Volumes ONTAP 工作环境时，如果尚未部署 Connector ，则 Cloud Manager 会提示您部署一个。



==== 规划您的配置

[role="quick-margin-para"]
Cloud Manager 可提供符合您的工作负载要求的预配置软件包，您也可以创建自己的配置。如果您选择自己的配置、则应了解可用的选项。 link:task_planning_your_config.html["了解更多信息。"]。



==== 设置网络

. 确保您的 VPC 和子网支持连接器和 Cloud Volumes ONTAP 之间的连接。
. 从目标 VPC 启用出站 Internet 访问，以便连接器和 Cloud Volumes ONTAP 可以联系多个端点。
+
此步骤非常重要，因为没有出站 Internet 访问， Connector 无法管理 Cloud Volumes ONTAP 。如果需要限制出站连接，请参阅的端点列表 link:reference_networking_aws.html["连接器和 Cloud Volumes ONTAP"]。

. 将 VPC 端点设置为 S3 服务。
+
如果要将冷数据从 Cloud Volumes ONTAP 分层到低成本对象存储，则需要 VPC 端点。



[role="quick-margin-para"]
link:reference_networking_aws.html["详细了解网络要求"]。



==== 设置 AWS KMS

[role="quick-margin-para"]
如果要对 Cloud Volumes ONTAP 使用 Amazon 加密，则需要确保存在有效的客户主密钥（ CMK ）。此外，您还需要通过添加 IAM 角色来修改每个 CMK 的密钥策略，该角色以 _key user_ 的身份为 Connector 提供权限。 link:task_setting_up_kms.html["了解更多信息。"]。



==== 使用 Cloud Manager 启动 Cloud Volumes ONTAP

[role="quick-margin-para"]
单击 * 添加工作环境 * ，选择要部署的系统类型，然后完成向导中的步骤。 link:task_deploying_otc_aws.html["阅读分步说明"]。

.相关链接
* link:concept_evaluating.html["评估"]
* link:task_creating_connectors_aws.html["使用 Cloud Manager 创建连接器"]
* link:task_launching_aws_mktp.html["从 AWS Marketplace 启动 Connector"]
* link:task_installing_linux.html["在 Linux 主机上安装 Connector 软件"]
* link:reference_permissions.html#what-cloud-manager-does-with-aws-permissions["Cloud Manager 如何使用 AWS 权限"]

